# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - datadog-cloud-integration-toggle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://datadogcloudintegrationtoggle.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6764c98c38c54657a71dd9f9846cc118 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a7e75fc09eca409f94e96e188ae4cf40 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: datadogcloudintegrationtoggle.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6764c98c38c54657a71dd9f9846cc118 }}/image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'datadog-cloud-integration-toggle'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_29fd59cd302143fd895c2dd1458ee779 }}
        images: 'datadogcloudintegrationtoggle.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6764c98c38c54657a71dd9f9846cc118 }}/image:${{ github.sha }}'